apiVersion: batch/v1
kind: CronJob
metadata:
  name: reminder

spec:
  schedule: 0 7 * * *
  timeZone: Europe/Stockholm
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: reminder
              image: registry.home.dennisskoko.com/birthday/reminder:latest
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ['ALL']
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              envFrom:
                - secretRef:
                    name: env
              env:
                - name: BIRTHDAY_ENDPOINT
                  value: http://api
